# Generated by Django 4.2.23 on 2025-07-27 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Unique identifier from the source (can be URL hash if no ID available)",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(help_text="Job title", max_length=255)),
                ("company", models.CharField(help_text="Company name", max_length=255)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Job location (can be 'Remote', city, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(help_text="Full job description")),
                ("url", models.URLField(help_text="Direct link to the job posting")),
                (
                    "source",
                    models.CharField(
                        help_text="Source identifier (e.g., 'greenhouse', 'weworkremotely')",
                        max_length=50,
                    ),
                ),
                (
                    "date_posted",
                    models.DateField(
                        blank=True,
                        help_text="Date the job was originally posted (from source)",
                        null=True,
                    ),
                ),
                (
                    "date_scraped",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this job was scraped by our system",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this job posting is still active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_scraped", "-date_posted"],
                "indexes": [
                    models.Index(
                        fields=["source", "date_scraped"],
                        name="jobscraper__source_9fa531_idx",
                    ),
                    models.Index(
                        fields=["company"], name="jobscraper__company_e84166_idx"
                    ),
                    models.Index(
                        fields=["location"], name="jobscraper__locatio_74e6c7_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="jobscraper__is_acti_4d8823_idx"
                    ),
                ],
                "unique_together": {("external_id", "source")},
            },
        ),
    ]
