# Generated by Django 4.2.23 on 2025-07-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobscraper", "0002_alter_jobposting_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="application_deadline",
            field=models.DateField(
                blank=True, help_text="Application deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="application_method",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Apply"),
                    ("email", "Email Application"),
                    ("third-party", "Third-party Portal"),
                    ("company-website", "Company Website"),
                    ("recruiter", "Contact Recruiter"),
                ],
                default="direct",
                help_text="How to apply for this job",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="benefits",
            field=models.JSONField(
                blank=True, default=list, help_text="List of benefits offered"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="bonus_equity",
            field=models.TextField(
                blank=True,
                help_text="Stock options, performance bonuses, equity details",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="certifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Required or preferred certifications",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Company rating (e.g., from Glassdoor)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("startup", "Startup (1-50)"),
                    ("small", "Small (51-200)"),
                    ("medium", "Medium (201-1000)"),
                    ("large", "Large (1001-5000)"),
                    ("enterprise", "Enterprise (5000+)"),
                ],
                help_text="Company size category",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_website",
            field=models.URLField(
                blank=True, help_text="Company homepage URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="compensation_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("annual", "Annual"),
                    ("monthly", "Monthly"),
                    ("weekly", "Weekly"),
                    ("daily", "Daily"),
                    ("commission", "Commission-based"),
                    ("contract", "Contract Rate"),
                ],
                default="annual",
                help_text="Type of compensation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="Currency code (USD, EUR, INR, etc.)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high-school", "High School"),
                    ("associate", "Associate's Degree"),
                    ("bachelor", "Bachelor's Degree"),
                    ("master", "Master's Degree"),
                    ("phd", "PhD"),
                    ("professional", "Professional Degree"),
                    ("none", "No Degree Required"),
                ],
                help_text="Required education level",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="employment_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on-site", "On-site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                help_text="Work arrangement",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Entry Level"),
                    ("junior", "Junior"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                    ("principal", "Principal"),
                    ("executive", "Executive"),
                    ("director", "Director"),
                ],
                help_text="Required experience level",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="hiring_manager",
            field=models.CharField(
                blank=True,
                help_text="Hiring manager or recruiter contact",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Industry/sector (e.g., Tech, Finance, Healthcare)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_category",
            field=models.CharField(
                blank=True,
                help_text="Derived job category (e.g., Software Engineering → Backend)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full-time", "Full-time"),
                    ("part-time", "Part-time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                    ("temporary", "Temporary"),
                    ("volunteer", "Volunteer"),
                ],
                help_text="Employment type",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Extracted keywords for searchability",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="languages_required",
            field=models.JSONField(
                blank=True, default=list, help_text="Required languages"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="number_of_openings",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of positions available"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="parse_confidence",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Confidence score of the parsing (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="projects_portfolio_examples",
            field=models.TextField(
                blank=True,
                help_text="Required project examples or portfolio requirements",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw scraped data for debugging"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="relocation_assistance",
            field=models.BooleanField(
                default=False, help_text="Whether relocation assistance is provided"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="Required qualifications and skills", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="responsibilities",
            field=models.TextField(
                blank=True, help_text="Specific duties and expectations", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="salary_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum salary",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="salary_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum salary",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="seniority_score",
            field=models.IntegerField(
                default=0, help_text="Parsed seniority level (0-10 scale)"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills_preferred",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of preferred/nice-to-have skills",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills_required",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of required hard and soft skills",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="tools_technologies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Specific software, frameworks, or platforms",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="travel_requirements",
            field=models.CharField(
                blank=True,
                help_text="Travel percentage or requirements",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="visa_sponsorship",
            field=models.BooleanField(
                default=False, help_text="Whether visa sponsorship is available"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["job_type"], name="jobscraper__job_typ_4130f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["employment_mode"], name="jobscraper__employm_54cec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["experience_level"], name="jobscraper__experie_cea734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["industry"], name="jobscraper__industr_e8785a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["salary_min", "salary_max"],
                name="jobscraper__salary__31e23e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["date_posted"], name="jobscraper__date_po_4d09c0_idx"
            ),
        ),
    ]
