# Generated by Django 4.2.23 on 2025-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobscraper", "0003_jobposting_application_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="company_logo",
            field=models.URLField(
                blank=True, help_text="URL to company logo image", null=True
            ),
        ),
    ]
