# Generated by Django 4.2.23 on 2025-08-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobscraper", "0005_jobposting_recruiter_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobposting",
            new_name="jobscraper__source__862b13_idx",
            old_name="jobscraper_jobposting_source_type_owner_idx",
        ),
    ]
