# Generated by Django 4.2.23 on 2025-08-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobscraper",
            "0006_rename_jobscraper_jobposting_source_type_owner_idx_jobscraper__source__862b13_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="summary",
            field=models.CharField(
                blank=True,
                help_text="Short plain-text summary for listings",
                max_length=500,
                null=True,
            ),
        ),
    ]
