# Generated by Django 4.2.23 on 2025-07-30 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobscraper", "0002_alter_jobposting_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the applicant", max_length=200
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address", max_length=254
                    ),
                ),
                ("phone", models.CharField(help_text="Phone number", max_length=20)),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn profile URL", null=True
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True,
                        help_text="Portfolio or personal website URL",
                        null=True,
                    ),
                ),
                (
                    "resume",
                    models.FileField(help_text="Resume file", upload_to="resumes/"),
                ),
                (
                    "cover_letter",
                    models.FileField(
                        blank=True,
                        help_text="Cover letter template",
                        null=True,
                        upload_to="cover_letters/",
                    ),
                ),
                ("address", models.TextField(help_text="Full address")),
                (
                    "work_authorization",
                    models.CharField(
                        help_text="Work authorization status (e.g., 'US Citizen', 'H1B', 'OPT', etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "custom_ats_answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom answers for common ATS questions stored as key-value pairs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "application_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the application",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_method",
                    models.CharField(
                        choices=[
                            ("API", "API"),
                            ("Browser", "Browser"),
                            ("Redirect", "Redirect"),
                        ],
                        help_text="Method used to submit the application",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        help_text="Current status of the application",
                        max_length=10,
                    ),
                ),
                (
                    "resume_used",
                    models.FileField(
                        blank=True,
                        help_text="Resume file used for this specific application",
                        null=True,
                        upload_to="application_resumes/",
                    ),
                ),
                (
                    "cover_letter_used",
                    models.FileField(
                        blank=True,
                        help_text="Cover letter used for this specific application",
                        null=True,
                        upload_to="application_cover_letters/",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the application was submitted",
                    ),
                ),
                (
                    "confirmation_number",
                    models.CharField(
                        blank=True,
                        help_text="Confirmation number or ID from the ATS system",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the application process",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if application failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        help_text="The job posting this application is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobscraper.jobposting",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        help_text="The user profile used for this application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobapplier.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-applied_at"],
                "unique_together": {("job", "user_profile")},
            },
        ),
    ]
