# Generated by Django 4.2.23 on 2025-08-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobapplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("applied", "Applied"),
                    ("failed", "Failed"),
                    ("rejected", "Rejected"),
                    ("interview", "Interview"),
                    ("offer", "Offer"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                help_text="Current status of the application",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("interview", "Interview"),
                            ("rejected", "Rejected"),
                            ("offer", "Offer"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        help_text="New status of the application",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user_manual", "User Manual"),
                            ("email_parse", "Email Parse"),
                            ("ats_sync", "ATS Sync"),
                        ],
                        default="user_manual",
                        help_text="Source of the status update",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or details about the status change",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this status update occurred"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="The application this status update belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="jobapplier.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Status History",
                "verbose_name_plural": "Application Status Histories",
                "ordering": ["-updated_at"],
            },
        ),
    ]
