# Generated by Django 4.2.23 on 2025-08-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapplier", "0004_add_verification_fields"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS jobapplier_applicationstatushistory CASCADE;"
            ),
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS jobapplier_userprofile CASCADE;"
            ),
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS jobapplier_application CASCADE;"
            ),
            reverse_sql="",
        ),
    ]
