# Generated by Django 4.2.23 on 2025-08-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapplier", "0006_remove_applicationstatushistory_application_and_more"),
    ]

    operations = [
        # 0005 drops legacy tables via raw SQL IF EXISTS. On fresh DBs, tables won't exist,
        # so performing DB-level RemoveField/DeleteModel causes errors. Keep only state changes.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="Application"),
                migrations.DeleteModel(name="ApplicationStatusHistory"),
                migrations.DeleteModel(name="UserProfile"),
            ],
        )
    ]
