# Generated by Django 5.2.4 on 2025-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekeronboarding",
            name="resume_url",
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="availability_date",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="benefits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="company_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="industries",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="job_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="preferred_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="resume",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="salary_max",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="salary_min",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="jobseekeronboarding",
            name="work_arrangement",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
