# Generated by Django 4.2.23 on 2025-07-27 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0002_remove_jobseekeronboarding_resume_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("profile_image_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("resume_url", models.URLField(blank=True)),
                ("resume_filename", models.CharField(blank=True, max_length=255)),
                ("cover_letter_url", models.URLField(blank=True)),
                ("cover_letter_filename", models.CharField(blank=True, max_length=255)),
                ("portfolio_pdf_url", models.URLField(blank=True)),
                (
                    "portfolio_pdf_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                ("profile_image_data", models.BinaryField(blank=True, null=True)),
                (
                    "profile_image_content_type",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "profile_image_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                ("profile_image_size", models.IntegerField(blank=True, null=True)),
                ("resume_data", models.BinaryField(blank=True, null=True)),
                ("resume_content_type", models.CharField(blank=True, max_length=100)),
                ("resume_size", models.IntegerField(blank=True, null=True)),
                ("cover_letter_data", models.BinaryField(blank=True, null=True)),
                (
                    "cover_letter_content_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("cover_letter_size", models.IntegerField(blank=True, null=True)),
                ("portfolio_pdf_data", models.BinaryField(blank=True, null=True)),
                (
                    "portfolio_pdf_content_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("portfolio_pdf_size", models.IntegerField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_level", models.CharField(blank=True, max_length=50)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("education", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("job_types", models.JSONField(blank=True, default=list)),
                ("work_arrangement", models.CharField(blank=True, max_length=50)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(blank=True, default="USD", max_length=10),
                ),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                ("industries", models.JSONField(blank=True, default=list)),
                (
                    "company_size_preference",
                    models.CharField(blank=True, max_length=50),
                ),
                ("benefits_preferences", models.JSONField(blank=True, default=list)),
                ("availability_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobseeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fyndr_auth_jobseekerprofile",
            },
        ),
        migrations.DeleteModel(
            name="JobSeekerOnboarding",
        ),
    ]
