# Generated by Django 4.2.23 on 2025-07-26 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0002_remove_jobseekeronboarding_resume_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("company_size", models.CharField(blank=True, max_length=50)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("mission_statement", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("company_brochure_url", models.URLField(blank=True)),
                (
                    "company_brochure_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                ("company_values", models.JSONField(blank=True, default=list)),
                ("company_benefits", models.JSONField(blank=True, default=list)),
                ("work_environment", models.CharField(blank=True, max_length=50)),
                ("dei_commitment", models.TextField(blank=True)),
                ("diversity_goals", models.JSONField(blank=True, default=list)),
                ("inclusion_policies", models.JSONField(blank=True, default=list)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("hr_contact_name", models.CharField(blank=True, max_length=100)),
                ("hr_contact_email", models.EmailField(blank=True, max_length=254)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("profile_image_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("resume_url", models.URLField(blank=True)),
                ("resume_filename", models.CharField(blank=True, max_length=255)),
                ("cover_letter_url", models.URLField(blank=True)),
                ("cover_letter_filename", models.CharField(blank=True, max_length=255)),
                ("portfolio_pdf_url", models.URLField(blank=True)),
                (
                    "portfolio_pdf_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_level", models.CharField(blank=True, max_length=50)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("education", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("job_types", models.JSONField(blank=True, default=list)),
                ("work_arrangement", models.CharField(blank=True, max_length=50)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=10)),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                ("industries", models.JSONField(blank=True, default=list)),
                (
                    "company_size_preference",
                    models.CharField(blank=True, max_length=50),
                ),
                ("benefits_preferences", models.JSONField(blank=True, default=list)),
                ("availability_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobseeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("profile_image_url", models.URLField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("specializations", models.JSONField(blank=True, default=list)),
                ("linkedin_url", models.URLField(blank=True)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("company_website", models.URLField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="recruiteremployeronboarding",
            name="user",
        ),
        migrations.DeleteModel(
            name="JobSeekerOnboarding",
        ),
        migrations.DeleteModel(
            name="RecruiterEmployerOnboarding",
        ),
    ]
