# Generated by Django 4.2.23 on 2025-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fyndr_auth",
            "0003_jobseekerprofile_delete_jobseekeronboarding",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="company_brochure_file",
            field=models.FileField(
                blank=True, null=True, upload_to="company_brochures/"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo_file",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="cover_letter_file",
            field=models.FileField(blank=True, null=True, upload_to="cover_letters/"),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="portfolio_pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="portfolios/"),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
