# Generated by Django 4.2.23 on 2025-07-30 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0003_jobseekerprofile_delete_jobseekeronboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("company_size", models.CharField(blank=True, max_length=50)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("mission_statement", models.TextField(blank=True)),
                ("logo_data", models.BinaryField(blank=True, null=True)),
                ("logo_filename", models.CharField(blank=True, max_length=255)),
                ("logo_content_type", models.CharField(blank=True, max_length=100)),
                ("logo_size", models.IntegerField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True)),
                ("company_brochure_data", models.BinaryField(blank=True, null=True)),
                (
                    "company_brochure_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "company_brochure_content_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("company_brochure_size", models.IntegerField(blank=True, null=True)),
                ("company_brochure_url", models.URLField(blank=True)),
                ("company_values", models.JSONField(blank=True, default=list)),
                ("company_benefits", models.JSONField(blank=True, default=list)),
                ("work_environment", models.CharField(blank=True, max_length=50)),
                ("dei_commitment", models.TextField(blank=True)),
                ("diversity_goals", models.JSONField(blank=True, default=list)),
                ("inclusion_policies", models.JSONField(blank=True, default=list)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("hr_contact_name", models.CharField(blank=True, max_length=100)),
                ("hr_contact_email", models.EmailField(blank=True, max_length=254)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyRecruiterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("recruiter", "Recruiter"),
                            ("hiring_manager", "Hiring Manager"),
                            ("viewer", "Viewer"),
                        ],
                        default="recruiter",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_relationships",
                        to="fyndr_auth.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("profile_image_data", models.BinaryField(blank=True, null=True)),
                (
                    "profile_image_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "profile_image_content_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("profile_image_size", models.IntegerField(blank=True, null=True)),
                ("profile_image_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("specializations", models.JSONField(blank=True, default=list)),
                ("industries", models.JSONField(blank=True, default=list)),
                ("resume_data", models.BinaryField(blank=True, null=True)),
                ("resume_filename", models.CharField(blank=True, max_length=255)),
                ("resume_content_type", models.CharField(blank=True, max_length=100)),
                ("resume_size", models.IntegerField(blank=True, null=True)),
                ("resume_url", models.URLField(blank=True)),
                ("company_associations", models.JSONField(blank=True, default=list)),
                ("current_company_id", models.IntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="salary_currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Job Seeker"),
                    ("recruiter", "Recruiter"),
                    ("company", "Company"),
                    ("administrator", "Administrator"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="jobseekerprofile",
            table=None,
        ),
        migrations.DeleteModel(
            name="RecruiterEmployerOnboarding",
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruiter_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companyrecruiterrelationship",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_relationships",
                to="fyndr_auth.recruiterprofile",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyrecruiterrelationship",
            unique_together={("company", "recruiter")},
        ),
    ]
