# Generated by Django 4.2.23 on 2025-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0004_companyprofile_company_brochure_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_image_file",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
