# Generated by Django 4.2.23 on 2025-07-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0005_jobseekerprofile_profile_image_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_brochure_file",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="logo_file",
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="cover_letter_file",
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="portfolio_pdf_file",
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="profile_image_file",
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="resume_file",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_brochure_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_brochure_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_brochure_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="cover_letter_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="cover_letter_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="cover_letter_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="portfolio_pdf_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="portfolio_pdf_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="portfolio_pdf_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_image_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_image_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="resume_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="resume_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="resume_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
