# Generated by Django on 2025-08-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # Point this legacy file to a valid dependency and no-op to avoid NodeNotFound
    dependencies = [
        ('fyndr_auth', '0008_rename_company_name_recruiterprofile_resume_filename_and_more'),
    ]

    operations = []
