# Generated by Django 4.2.23 on 2025-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0006_remove_companyprofile_company_brochure_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_image_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_image_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
