# Generated by Django 4.2.23 on 2025-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0006_oauthtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthtoken",
            name="provider",
            field=models.CharField(choices=[("google", "Google")], max_length=50),
        ),
    ]
