# Generated by Django 4.2.23 on 2025-07-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0007_recruiterprofile_profile_image_content_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruiterprofile",
            old_name="company_name",
            new_name="resume_filename",
        ),
        migrations.RenameField(
            model_name="recruiterprofile",
            old_name="company_website",
            new_name="resume_url",
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="company_associations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="current_company_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="industries",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="resume_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="resume_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="resume_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Job Seeker"),
                    ("recruiter", "Recruiter"),
                    ("company", "Company"),
                    ("administrator", "Administrator"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CompanyRecruiterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("recruiter", "Recruiter"),
                            ("hiring_manager", "Hiring Manager"),
                            ("viewer", "Viewer"),
                        ],
                        default="recruiter",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_relationships",
                        to="fyndr_auth.companyprofile",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_relationships",
                        to="fyndr_auth.recruiterprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "recruiter")},
            },
        ),
    ]
