# Generated by Django 4.2.23 on 2025-08-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0006_oauthtoken"),
        ("fyndr_auth", "0009_oauthtoken"),
    ]

    operations = []
