# Generated by Django 4.2.23 on 2025-08-14 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0010_merge_0006_oauthtoken_0009_oauthtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthtoken",
            name="provider",
            field=models.CharField(choices=[("google", "Google")], max_length=50),
        ),
        migrations.CreateModel(
            name="PortalCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("workday", "Workday"),
                            ("site", "Company Site"),
                        ],
                        max_length=50,
                    ),
                ),
                ("company_domain", models.CharField(blank=True, max_length=255)),
                ("username_encrypted", models.BinaryField()),
                ("password_encrypted", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider", "company_domain")},
            },
        ),
    ]
