# Generated by Django 4.2.23 on 2025-08-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0014_location_model_and_seed"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="location",
            new_name="fyndr_auth__city_9c392f_idx",
            old_name="fyndr_auth_city_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="fyndr_auth__state_f9def9_idx",
            old_name="fyndr_auth_state_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="fyndr_auth__country_5a67d1_idx",
            old_name="fyndr_auth_country_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="fyndr_auth__display_b5b90f_idx",
            old_name="fyndr_auth_display_idx",
        ),
    ]
