# Generated by Django 4.2.23 on 2025-08-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0002_skills_roles_preferred_roles"),
        (
            "fyndr_auth",
            "0015_rename_fyndr_auth_city_idx_fyndr_auth__city_9c392f_idx_and_more",
        ),
    ]

    operations = []
