# Generated by Django 4.2.23 on 2025-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0019_seed_more_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrole",
            name="for_jobseekers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobrole",
            name="for_recruiters",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(fields=["title"], name="fyndr_auth__title_388ff6_idx"),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["normalized_title"], name="fyndr_auth__normali_c16f18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["category"], name="fyndr_auth__categor_9efd3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["-popularity"], name="fyndr_auth__popular_63a556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="fyndr_auth__name_45b0c1_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["category"], name="fyndr_auth__categor_47af19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["-popularity"], name="fyndr_auth__popular_ad180e_idx"
            ),
        ),
    ]
