# Generated by Django 4.2.23 on 2025-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0023_seed_more_recruiter_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="work_arrangements",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
