# Generated by Django 4.2.23 on 2025-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0024_jobseekerprofile_work_arrangements"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="onboarding_step",
            field=models.IntegerField(default=1),
        ),
    ]
