# Generated by Django 4.2.23 on 2025-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0025_jobseekerprofile_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=150, unique=True)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("popularity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["label"], name="fyndr_auth__label_4c1771_idx"),
                    models.Index(
                        fields=["currency"], name="fyndr_auth__currenc_88fc8b_idx"
                    ),
                    models.Index(
                        fields=["-popularity"], name="fyndr_auth__popular_c9016d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("popularity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="fyndr_auth__name_c0ce11_idx"),
                    models.Index(
                        fields=["category"], name="fyndr_auth__categor_a9914c_idx"
                    ),
                    models.Index(
                        fields=["-popularity"], name="fyndr_auth__popular_990a28_idx"
                    ),
                ],
            },
        ),
    ]
