# Generated by Django 4.2.23 on 2025-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0026_salaryband_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="experiences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="education",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="experiences",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
