# Generated by Django 4.2.23 on 2025-08-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0027_jobseekerprofile_experiences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="card_brand",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="card_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="payment_methods",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
