# Generated by Django 4.2.23 on 2025-08-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0032_jobseekerprofile_suited_job_roles_detailed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="skills_detailed",
        ),
    ]
